### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by samccann** [geerlingguy/operator-sdk-performance-testing#23]
Hey @geerlingguy  - We're doing a general cleanup of repos in the ansible-community org to archive those repos no longer in use.

Is this repo still valid? It hasn't had activity for a few years, but unsure if that means it's still in use somewhere.

**Comment by geerlingguy** [comment]
No, it was mainly used in testing some performance improvements we were making at the time. It has not really been used since, so feel free to archive it! Thanks :)

**Comment by samccann** [comment]
Cool thanks!
